version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: openjdk:8
    working_directory: /src
    environment:
      - SBT_VERSION: 1.2.6
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - run:
          name: Get sbt binary
          command: |
                    apt update && apt install -y curl
                    curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
                    dpkg -i sbt-$SBT_VERSION.deb
                    rm sbt-$SBT_VERSION.deb
                    apt-get update
                    apt-get install -y sbt python-pip git
                    pip install awscli
                    apt-get clean && apt-get autoclean
      - checkout
      - run:
          name: Build dx2db
          command: </dev/null sbt dx2dbJVM/run
      - run:
          name: Build dx2plan.js
          command: </dev/null sbt dx2plan/fullOptJS
      - run:
          name: Make sure the tree is still clean
          command: git diff --exit-code > /dev/null
      - deploy:
          name: Deploy
          command: |
            git config --global user.email "3079085+b0lt@users.noreply.github.com"
            git config --global user.name b0lt

            mkdir -p /tmp
            git clone $CIRCLE_REPOSITORY_URL /tmp/gh-pages -b gh-pages

            JS_OUTPUT_DIR=/src/dx2plan/.js/target/scala-2.12
            cp $JS_OUTPUT_DIR/dx2plan-opt.js $JS_OUTPUT_DIR/dx2plan-opt.js.map /tmp/gh-pages
            cp /src/dx2db/shared/src/main/resources/dx2db.json /tmp/gh-pages

            cd /tmp/gh-pages

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git push origin $TARGET_BRANCH
            fi
